name: Node.js CI # Имя процесса

on: push # Когда запускать: на каждый пуш

jobs:
  build:
    runs-on: ubuntu-latest # где запускать: на виртуальной машине Ubuntu

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x] # Матрица тестирования

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v4

      # Ставим Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm" # Кэширование зависимостей для скорости

      # Ставим зависимости
      - run: make install

      # Запускаем линтер
      # Если есть скрипт "lint" в package.json
      - run: make lint

      # Запускаем тесты
      - run: make test
